config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up", to: "rails/health#show", as: :rails_health_check

  # I don't exactly understand why omniauth calls this local route instead of the
  # FranceConnect one in features, there might be a better configuration to do :shrug:
  get "/api/v1/logout", to: "home#index" if Rails.env.test?
  get "/api/v2/session/end", to: "home#index" if Rails.env.test?

  get "/callback", to: "sessions#create"
  delete "/logout", to: "sessions#destroy", as: :logout
  get "/logout-callback", to: "sessions#fc_callback", as: :fc_logout_callback
  get "/auth/failure", to: "errors#auth_failure"

  resources :collectivities, only: %i[index], path: "collectivites" do
    member do
      get :show, path: "me_connecter"
      get :no_france_connect, path: "sans_france_connect"
    end

    collection do
      get :select
    end

    get "/erreur", to: "shipments#error", as: :shipment_error
    get "/envoyer_mes_donnees", to: "shipments#new", as: :new_shipment
    get "/confirmation/:reference", to: "shipments#show", as: :shipment

    resources :shipments, only: %i[create], param: :reference
  end

  get "/cgu_usagers", to: "home#cgu_usagers"
  get "/cgu_administrations", to: "home#cgu_administrations"
  get "/accessibilite", to: "home#accessibilite"
  get "faq", to: "home#faq"
  get "/collectivites/:id", to: "collectivities#show", as: :simple_collectivity

  root "home#index"

  scope module: :api, path: "/api" do
    resources :collectivities, only: %i[index create show], path: "collectivites"

    resources :frontal, only: :index

    post "/datapass/webhook" => "datapass_webhooks#create"
  end

  mount GoodJob::Engine => "good_job"
end

app/models/collectivity.rb
class Collectivity < ApplicationRecord
  TEST_SIRETS = %w[11111111111111 11111111111112].freeze

  enum :status, {active: "active", inactive: "inactive"}
  validates :name, :siret, :code_cog, :status, :departement, presence: true
  validates :siret, uniqueness: true
  validates :siret, siret: true, unless: -> { test_siret? }

  has_many :shipments, dependent: :destroy

  def test_siret?
    TEST_SIRETS.include?(siret)
  end
end

app/controllers/api/collectivities_controller.rb
class Api::CollectivitiesController < Api::ApplicationController
  before_action :authenticate, only: :create

  def index
    render json: Collectivity.active.order(:name), each_serializer: Api::CollectivitiesSerializer
  end

  def show
    collectivity = Collectivity.active.find_by(code_cog: params[:id])

    if collectivity.nil?
      render json: {error: "Collectivity not found"}, status: :not_found
    else
      render json: collectivity, serializer: Api::CollectivitiesSerializer
    end
  end

  def create
    collectivity = Collectivity.build(collectivity_params)

    if collectivity.save
      render json: {collectivity: collectivity}, status: :created
    else
      status = collectivity.errors.of_kind?(:siret, :taken) ? :conflict : :unprocessable_entity
      render json: {errors: collectivity.errors}, status: status
    end
  end

  private

  def collectivity_params
    params.expect(collectivity: [:name, :siret, :code_cog, :status, :editor, :departement])
  end
end

app/controllers/collectivities_controller.rb
class CollectivitiesController < ApplicationController
  before_action :set_collectivity, only: %i[select show no_france_connect]
  before_action :move_params_to_session, only: :show

  def index
    @collectivities = Collectivity.active.order(:departement, :name).map do |collectivity|
      CollectivityDecorator.new(collectivity)
    end
  end

  def show
    @qr_code_url = simple_collectivity_url(@collectivity.siret)
    qrcode = RQRCode::QRCode.new(@qr_code_url)

    @qr_code = Base64.strict_encode64(qrcode.as_png(
      border_modules: 0,
      fill: :white,
      size: 480
    ).to_s)
  end

  def no_france_connect
  end

  def select
    if shipment_data_is_present?
      redirect_to collectivity_new_shipment_path(@collectivity.siret)
    else
      redirect_to collectivity_path(@collectivity.siret)
    end
  end

  private

  def move_params_to_session
    session[:external_id] ||= params[:external_id]
    session[:redirect_uri] ||= params[:redirect_uri]
    session[:siret] ||= @collectivity.siret
    SetupCurrentData.call(session: session, params: params)
  end

  def set_collectivity
    @collectivity = CollectivityDecorator.new(Collectivity.active.find_by!(siret: params[:id]))
  rescue ActiveRecord::RecordNotFound
    flash[:error] = {
      title: t(".not_found_error.title"),
      text: t(".not_found_error.text", siret: params[:id]),
    }

    redirect_to collectivities_path
  end

  def shipment_data_is_present?
    # TODO : I doubt it's the perfect way to check that
    # we should use the shipment validations once they'll exist
    Current.quotient_familial.present? && Current.pivot_identity.present?
  end
end

app/views/collectivities/_alternatives.html.erb
<% alternative_keys ||= [:caf, :msa] %>
<% alternatives = t('collectivities.no_france_connect.alternative_options').slice(*alternative_keys).values  %>

<%= simple_format t('collectivities.no_france_connect.alternative_text'), class: 'fr-mt-4w fr-mb-1w' %>

<ul class="fr-ml-2w">
  <% alternatives.each do |option| %>
    <%= simple_format option, { }, wrapper_tag: 'li' %>
  <% end %>
</ul>

<%= simple_format t('collectivities.no_france_connect.transmission_text'), class: 'fr-mt-4w fr-mb-1w' %>

<ul class="fr-ml-2w">
  <% t('collectivities.no_france_connect.transmission_options').each do |option| %>
    <%= simple_format option, { }, wrapper_tag: 'li' %>
  <% end %>
</ul>

app/views/collectivities/_show_banner.html.erb
<% content_for :banner_title do %>
  <%= simple_format t('collectivities.show.banner.text', label: @collectivity.display_name), { }, wrapper_tag: 'span' %>
<% end %>

<% content_for :banner_right do %>
  <%= render partial: "shared/banner_duration_and_link", locals: { duration: duration } %>
<% end %>

app/views/collectivities/index.html.erb
<% content_for :banner_title do %>
  <%= simple_format t('home.index.banner.text'), { }, wrapper_tag: 'span' %>
<% end %>

<% content_for :banner_right do %>
  <%= render partial: "shared/banner_duration_and_link", locals: { duration: 3 } %>
<% end %>

<%= simple_format t('.title'), { }, wrapper_tag: 'h2' %>

<%= form_with url: select_collectivities_path, method: :get, class: "fr-col-md-8" do |form| %>
  <div class="fr-select-group">
    
    <%= form.label :id, class: "fr-label" do %>
      <%= t('.form.label') %>

      <span class="fr-hint-text">
        <%= t('.form.hint') %>
      </span>
    <% end %>

    <%= form.select :id, options_from_collection_for_select(@collectivities, :siret, :select_name), { prompt: t('.form.prompt') }, { class: "fr-select", required: true } %>

    <div class="fr-notice fr-notice--info fr-mt-2w">
      <div class="fr-container">
        <div class="fr-notice__body">
          <p class="fr-notice__title">
            <%= t('.form.notice.text')%>
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="fr-grid-row fr-grid-row--right">
    <%= button_tag type: "submit", class: "fr-btn fr-btn--lg fr-btn--icon-right fr-fi-arrow-right-line" do %>
      <%= t('shared.next_button') %>
    <% end %>
  </div>
<% end %>

app/views/collectivities/no_france_connect.html.erb
<%= render partial: "show_banner", locals: { duration: 2 } %>

<div class="fr-col-md-8">
  <%= simple_format t('.title'), { }, wrapper_tag: 'h2' %>

  <%= simple_format t('.explanation'), { }, wrapper_tag: 'p' %>

  <%= render partial: "alternatives" %>

  <div class="fr-callout fr-icon-information-line fr-mt-6w">
    <h3 class="fr-callout__title">
      <%=t('.callout.title')%>
    </h3>
    <p class="fr-callout__text">
      <%=t('.callout.text')%>
    </p>
    <%= link_to t('.callout.button'), "https://form.typeform.com/to/sXL2WhOi", class: "fr-btn"%>
  </div>
</div>

app/views/collectivities/show.html.erb
<%= render partial: "show_banner", locals: { duration: 2 } %>

<div class="fr-col-md-8">
  <%= simple_format t('.title'), { }, wrapper_tag: 'h2' %>

  <p><%= t('.info.explanation') %></p>

  <div class="fr-grid-row fr-grid-row--center">
    <div class="fr-connect-group">
      <%= form_tag('/auth/france_connect', method: 'post', data: {turbo: false}) do %>
        <button type='submit' class="fr-connect">
          <span class="fr-connect__login">S'identifier avec</span>
          <span class="fr-connect__brand">FranceConnect</span>
        </button>
      <% end %>

      <p>
        <a href="https://franceconnect.gouv.fr/" target="_blank"  rel="noopener" title="Qu’est-ce que FranceConnect ? - nouvelle fenêtre">
          Qu’est-ce que FranceConnect ?
        </a>
      </p>
    </div>
  </div>

  <div class="fr-alert fr-alert--info">
    <h3 class="fr-alert__title"><%= t('.info.title') %></h3>
    <p><%= t('.info.content') %></p>    
    <p>
      <a class="fr-link--sm" href='/faq#donnees-personnelles'>
        <%= t('.info.link')%>
      </a>
    </p>
  </div>

  <div class="fr-grid-row fr-grid-row--center fr-mb-2w fr-mt-10w">
    <div class="horizontal-line"></div>
    <div class="fr-mx-4w">Ou</div>
    <div class="horizontal-line"></div>
  </div>

  <div class="fr-mb-6w">
    <div class="fr-grid-row fr-grid-row--center">
      <%= t('.no_france_connect.text') %>
    </div>

    <div class="fr-grid-row fr-grid-row--center">
      <%= link_to t('.no_france_connect.link'), no_france_connect_collectivity_path(@collectivity.siret), class: "fr-link fr-icon-arrow-right-line fr-link--icon-right" %>
    </div>
  </div>

</div>

<% content_for :secondary_information do %>
  <div class="fr-py-4w fr-mt-15w fr-background-alt--grey">
    <div class="fr-container">
      <div class="fr-grid-row">
        <div class="fr-col-md-8">
          <h3 class="fr-text-title--grey"><%= t(".secondary_info.title") %></h3>
          <p class="fr-text--lg"><%= t(".secondary_info.explanation", collectivity_name: @collectivity.display_name) %></p>

          <div class="fr-grid-row">
            <div class="fr-col-md-4 fr-col-12 fr-pr-md-2w">
              <%= image_tag "data:image/png;base64,#{@qr_code}", alt: "QR code vers le formulaire de #{@collectivity.display_name}, cette page", class: "fr-responsive-img" %>
            </div>

            <div class="fr-col-md-8 fr-col-12">
              <div class="fr-card fr-enlarge-link fr-card--download download-qr">
                <div class="fr-card__body">
                  <div class="fr-card__content">
                    <h3 class="fr-card__title">
                      <a href="data:image/png;base64,<%=@qr_code%>" id="download-btn" download="QRCode_<%=@collectivity.siret%>.jpg">
                        <%= t(".secondary_info.download") %>
                      </a>
                    </h3>

                    <div class="fr-card__end">
                      <p class="fr-card__detail">JPG – 480 x 480px</p>
                    </div>
                  </div>
                </div>
              </div>

              <div class="fr-my-2w">
                <div class="fr-mb-1w">
                  <strong><%= t(".secondary_info.link_title") %></strong> 
                </div>
                <%= link_to @qr_code_url, @qr_code_url, class: "break-link", title: "URL vers le formulaire de #{@collectivity.display_name}, cette page" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>