config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up", to: "rails/health#show", as: :rails_health_check

  # I don't exactly understand why omniauth calls this local route instead of the
  # FranceConnect one in features, there might be a better configuration to do :shrug:
  get "/api/v1/logout", to: "home#index" if Rails.env.test?
  get "/api/v2/session/end", to: "home#index" if Rails.env.test?

  get "/callback", to: "sessions#create"
  delete "/logout", to: "sessions#destroy", as: :logout
  get "/logout-callback", to: "sessions#fc_callback", as: :fc_logout_callback
  get "/auth/failure", to: "errors#auth_failure"

  resources :collectivities, only: %i[index], path: "collectivites" do
    member do
      get :show, path: "me_connecter"
      get :no_france_connect, path: "sans_france_connect"
    end

    collection do
      get :select
    end

    get "/erreur", to: "shipments#error", as: :shipment_error
    get "/envoyer_mes_donnees", to: "shipments#new", as: :new_shipment
    get "/confirmation/:reference", to: "shipments#show", as: :shipment

    resources :shipments, only: %i[create], param: :reference
  end

  get "/cgu_usagers", to: "home#cgu_usagers"
  get "/cgu_administrations", to: "home#cgu_administrations"
  get "/accessibilite", to: "home#accessibilite"
  get "faq", to: "home#faq"
  get "/collectivites/:id", to: "collectivities#show", as: :simple_collectivity

  root "home#index"

  scope module: :api, path: "/api" do
    resources :collectivities, only: %i[index create show], path: "collectivites"

    resources :frontal, only: :index

    post "/datapass/webhook" => "datapass_webhooks#create"
  end

  mount GoodJob::Engine => "good_job"
end

app/models/shipment.rb
class Shipment < ApplicationRecord
  enum :hubee_status, {pending: "pending", sent: "sent", si_received: "si_received", in_progress: "in_progress", done: "done", refused: "refused"}
  validates :reference, presence: true, uniqueness: true, length: {is: 13}
  validates_presence_of :hubee_case_id, :hubee_folder_id
  after_initialize :affect_reference

  belongs_to :collectivity

  def affect_reference
    return if persisted?
    reference = SecureRandom.hex[0...13].upcase

    if Shipment.where(reference: reference).any?
      affect_reference
    else
      self.reference = reference
    end
  end
end

app/controllers/shipments_controller.rb
class ShipmentsController < ApplicationController
  before_action :set_collectivity

  def show
    @shipment = Shipment.find_by(reference: params[:reference])
    @redirect_uri = Current.redirect_uri
  end

  def new
    @pivot_identity_facade = PivotIdentityFacade.new(Current.pivot_identity)
    @quotient_familial_facade = QuotientFamilialFacade.new(Current.quotient_familial)
  end

  def error
  end

  def create
    result = StoreQuotientFamilial.call(
      collectivity: Current.collectivity,
      external_id: Current.external_id,
      pivot_identity: Current.pivot_identity,
      original_pivot_identity: Current.original_pivot_identity,
      quotient_familial: Current.quotient_familial,
      user: Current.user
    )

    if result.success?
      redirect_to collectivity_shipment_path(@collectivity.siret, result.shipment.reference)
    else
      flash[:error] = {
        title: t(".hubee_error.title"),
        text: t(".hubee_error.text", collectivity: @collectivity.display_name),
      }

      redirect_to collectivity_shipment_error_path(Current.collectivity.siret)
    end
  end

  private

  def set_collectivity
    @collectivity = CollectivityDecorator.new(Current.collectivity)
  end
end

app/views/shipments/error.html.erb
<%= render partial: "collectivities/show_banner", locals: { duration: 1 } %>

<div class="fr-col-md-8">
  <h2><%= t('errors.title') %></h2>
  <%= render partial: "collectivities/alternatives" %>
</div>
<!--
  <%= raw JSON.pretty_generate(session.fetch("raw_info", {}).slice("sub", "idp_birthdate", "preferred_username", "birthcountry", "birthdate", "birthplace", "family_name", "given_name", "gender")) %>
-->

<!--
  <%= raw JSON.pretty_generate(session.fetch("quotient_familial", {})) %>
-->

app/views/shipments/new.html.erb
<%= render partial: "collectivities/show_banner", locals: { duration: 1 } %>

<div class="fr-col-md-8">
  <%= simple_format t('.title', collectivity_name: @collectivity.display_name), { }, wrapper_tag: 'h2' %>

  <div class="user-data fr-p-3w">
    <h3 class="fr-h4 underlined fr-pb-1w"><%= t('.quotient_familial.title', regime: @quotient_familial_facade.regime) %></h3>

    <% if @quotient_familial_facade.empty? %>
      <div class="fr-alert fr-alert--warning fr-alert--sm">
        <p><%= t('errors.no_data') %></p>
      </div>
    <% else %>
      <ul>
        <li>
          <strong><%= t('.quotient_familial.quotient', month_year: @quotient_familial_facade.month_year) %></strong>
          <br /><%= @quotient_familial_facade.value %>
        </li>

        <li>
          <strong><%= t('.allocataires') %></strong>
          <% @quotient_familial_facade.allocataires.each do |allocataire| %>
            <br /><%= allocataire %>
          <% end %>
        </li>

        <li>
          <strong><%= t('.children') %></strong>
          <% @quotient_familial_facade.children.each do |child| %>
            <br /><%= child %>
          <% end %>

          <% if @quotient_familial_facade.children.blank? %>
            <br /><%= t('.no_children') %>
          <% end %>
        </li>
      </ul>
    <% end %>

    <h3 class="fr-h4 underlined fr-pb-1w fr-mt-2w"><%= t('.france_connect.title') %></h3>

    <% if @pivot_identity_facade.empty? %>
      <div class="fr-alert fr-alert--warning fr-alert--sm">
        <p><%= t('errors.no_data') %></p>
      </div>
    <% else %>
      <%= simple_format @pivot_identity_facade.full_sentence, { }, wrapper_tag: 'p' %>
    <% end %>
  </div>

  <div class="fr-grid-row fr-my-3w">
    <div class="fr-col">
      <%= link_to t('shared.previous_button'), collectivities_path, class: "fr-btn fr-btn--secondary fr-btn--icon-left fr-fi-arrow-left-line fr-mb-1w" %>
    </div>

    <%= form_tag(collectivity_shipments_path(params[:collectivity_id]), method: 'post', data: {turbo: false}) do %>
      <%= button_tag type: :submit, class: "fr-btn fr-btn--lg fr-btn--icon-right fr-fi-arrow-right-line" do %>
        <%= simple_format t('.next_button', collectivity: @collectivity.display_name), { }, wrapper_tag: 'span' %>
      <% end %>
    <% end %>
  </div>

  <div class="fr-alert fr-alert--info">
    <h3 class="fr-alert__title"><%= t('.info.title') %></h3>
    <p class="fr-my-2w">
      <span class="fr-icon-success-fill success-green" aria-hidden="true"></span>
      <%=  t('.info.paragraph_1', collectivity: @collectivity.display_name) %>
    </p>
    <p>
      <span class="fr-icon-success-fill success-green" aria-hidden="true"></span>
      <%=  t('.info.paragraph_2', collectivity: @collectivity.display_name) %>
    </p>
    <p>
      <a class="fr-link--sm" href='/faq#donnees-personnelles'>
        <%= t('.info.link')%>
      </a>
    </p>
  </div>
  <!--
    <%= raw JSON.pretty_generate(session.fetch("raw_info", {}).slice("sub", "idp_birthdate", "preferred_username", "birthcountry", "birthdate", "birthplace", "family_name", "given_name", "gender")) %>
  -->

  <!--
    <%= raw JSON.pretty_generate(session.fetch("quotient_familial", {})) %>
  -->
</div>

app/views/shipments/show.html.erb
<%= render partial: "collectivities/show_banner", locals: { duration: 0 } %>

<div class="centered-text">
  <span class="fr-icon-success-fill big-icon success-green" aria-hidden="true"></span>
  <%= simple_format t('.title', label: @collectivity.display_name, code_cog: @collectivity.code_cog), { }, wrapper_tag: 'h2' %>
  <%= simple_format t('.reference', reference: @shipment.reference), class: "fr-text--lead fr-mt-3w" %>
  <% if @redirect_uri %>
    <%= link_to t('.redirect_cta'), @redirect_uri, class: "fr-btn fr-btn--secondary fr-btn--lg fr-btn--icon-right fr-icon-external-link-line fr-mt-3w" %>
  <% end %>


  <div class="fr-mt-12w">
    <a class="image-link" href="https://jedonnemonavis.numerique.gouv.fr/Demarches/3846?&view-mode=formulaire-avis&nd_source=button&key=ba28b0f85134e19f6dd7124d50d98ca2">
      <img src="https://jedonnemonavis.numerique.gouv.fr/static/bouton-bleu.svg" alt="Je donne mon avis" />
    </a>
  </div>
</div>