config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up", to: "rails/health#show", as: :rails_health_check

  # I don't exactly understand why omniauth calls this local route instead of the
  # FranceConnect one in features, there might be a better configuration to do :shrug:
  get "/api/v1/logout", to: "home#index" if Rails.env.test?
  get "/api/v2/session/end", to: "home#index" if Rails.env.test?

  get "/callback", to: "sessions#create"
  delete "/logout", to: "sessions#destroy", as: :logout
  get "/logout-callback", to: "sessions#fc_callback", as: :fc_logout_callback
  get "/auth/failure", to: "errors#auth_failure"

  resources :collectivities, only: %i[index], path: "collectivites" do
    member do
      get :show, path: "me_connecter"
      get :no_france_connect, path: "sans_france_connect"
    end

    collection do
      get :select
    end

    get "/erreur", to: "shipments#error", as: :shipment_error
    get "/envoyer_mes_donnees", to: "shipments#new", as: :new_shipment
    get "/confirmation/:reference", to: "shipments#show", as: :shipment

    resources :shipments, only: %i[create], param: :reference
  end

  get "/cgu_usagers", to: "home#cgu_usagers"
  get "/cgu_administrations", to: "home#cgu_administrations"
  get "/accessibilite", to: "home#accessibilite"
  get "faq", to: "home#faq"
  get "/collectivites/:id", to: "collectivities#show", as: :simple_collectivity

  root "home#index"

  scope module: :api, path: "/api" do
    resources :collectivities, only: %i[index create show], path: "collectivites"

    resources :frontal, only: :index

    post "/datapass/webhook" => "datapass_webhooks#create"
  end

  mount GoodJob::Engine => "good_job"
end

app/views/layouts/_analytics.html.erb
<!-- Matomo -->
<script>
  var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(["setExcludedQueryParams", ["simulationId","_csrf"]]);
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="https://stats.data.gouv.fr/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '305']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Matomo Code -->

app/views/layouts/_banner.html.erb
  <% if content_for? :banner_title %>
  <div class="banner fr-py-4w">
    <div class="fr-container">
      <div class="fr-container fr-px-0">
        <div class="fr-grid-row fr-grid-row--gutters">
          <div class="fr-col">
            <h1 class="fr-h2 unbold">
              <%= yield :banner_title %>
            </h1>
          </div>

          <% if content_for? :banner_right %>
            <div class="fr-col-12 fr-col-md-3">
              <%= yield :banner_right %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<div class="fr-col-md-8">
  <% flash.each do |key, value| %>
    <div class="fr-alert fr-alert--<%=key%> fr-mb-3w">
      <h4 class="fr-alert__title"><%=value[:title] || "Erreur"%></h4>
      <%= simple_format (value[:text] || value), { }, wrapper_tag: 'p' %>

      <% if key == 'error' %>
        <p class="fr-mt-2w">
          <span class="fr-icon-settings-5-fill" aria-hidden="true"></span>
          <%= simple_format t('errors.report_sent'), { }, wrapper_tag: 'span' %>
        </p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="fr-footer" role="contentinfo" id="footer">
  <div class="fr-container">
    <div class="fr-footer__body">
      <div class="fr-footer__brand fr-enlarge-link">
        <a href="/" title="<%= t('home.index.title')%> - <%= t('layout.title') %>">
          <%= simple_format t('layout.entity'), { class: 'fr-logo' }, wrapper_tag: 'p' %>
        </a>
      </div>
      <div class="fr-footer__content">
        <p class="fr-footer__content-desc">
          <%= t('footer.tagline')%>
        </p>
        <ul class="fr-footer__content-list">
          <% t('footer.external_links').each do |external_link| %>
            <li class="fr-footer__content-item">
              <a class="fr-footer__content-link" href="https://<%= external_link %>" target="_blank" rel="noopener external" title="<%= external_link%> - nouvelle fenêtre">
                <%= external_link %>
              </a>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="fr-footer__bottom">
      <ul class="fr-footer__bottom-list">
        <li class="fr-footer__bottom-item">
          <a class="fr-footer__bottom-link" href="/accessibilite">Accessibilité : totalement conforme</a>
        </li>
        <li class="fr-footer__bottom-item">
          <a class="fr-footer__bottom-link" href="/cgu_usagers">Conditions Générales d'utilisations - Usagers</a>
        </li>
        <li class="fr-footer__bottom-item">
          <a class="fr-footer__bottom-link" href="/cgu_administrations">Conditions Générales d'utilisations - Administrations</a>
        </li>
        <li class="fr-footer__bottom-item">
          <a class="fr-footer__bottom-link" href="/cgu_usagers#3-traitement-des-donn-es-caract-re-personnel">Données personnelles</a>
        </li>
        <li class="fr-footer__bottom-item">
          <a class="fr-footer__bottom-link" href="/cgu_usagers#2-3-cookies-et-mesures-d-audience">Gestion des cookies</a>
        </li>
      </ul>
      <div class="fr-footer__bottom-copy">
        <p>Sauf mention explicite de propriété intellectuelle détenue par des tiers, les contenus de ce site sont proposés sous <%= external_link("licence etalab-2.0", "https://github.com/etalab/licence-ouverte/blob/master/LO.md") %>
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header role="banner" class="fr-header" id="header-navigation">
  <div class="fr-header__body">
    <div class="fr-container">
      <div class="fr-header__body-row">
        <div class="fr-header__brand fr-enlarge-link">
          <div class="fr-header__brand-top">
            <div class="fr-header__logo">
              <%= simple_format t('layout.entity'), { class: 'fr-logo' }, wrapper_tag: 'p' %>
            </div>
            <div class="fr-header__navbar">
              <button class="fr-btn--menu fr-btn" data-fr-opened="false" aria-controls="modal-499" aria-haspopup="menu" id="button-500" title="Menu">
                Menu
              </button>
            </div>
          </div>
          <div class="fr-header__service">
            <a href="/" title="<%= t('home.index.title')%> - <%= t('layout.title') %>">
              <p class="fr-header__service-title">
                <%=t('header.title.bold_part')%><i class="unbold"><%=t('header.title.italic_part')%></i>
              </p>
            </a>
            <p class="fr-header__service-tagline">
              <%= t('layout.tagline') %>
            </p>
          </div>
        </div>
        <div class="fr-header__tools">
           <div class="fr-header__tools-links">
            <div class="two-rows-headers">
              <% if Current.user.authenticated? %>
                <div class="fr-mr-1w fr-mb-1w">
                  <%= Current.user.display_name %>
                </div>
              <% end %>

              <ul class="fr-btns-group">
                <li>
                  <%= link_to t('header.faq'), faq_path, class: "fr-btn fr-icon-information-fill" %>
                </li>

                <% if Current.user.authenticated? %>
                  <li>
                    <%= button_to t('header.logout'), logout_path, method: :delete, class: "fr-btn fr-icon-account-line", data: {turbo: false} %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="fr-header__menu fr-modal" id="modal-499" aria-labelledby="button-500">
    <div class="fr-container">
      <button class="fr-btn--close fr-btn" aria-controls="modal-499" title="Fermer">
        Fermer
      </button>
      <div class="fr-header__menu-links">
      </div>
    </div>
  </div>
</header>

app/views/layouts/_skiplinks.html.erb
<div class="fr-skiplinks">
  <nav class="fr-container" role="navigation" aria-label="Accès rapide">
    <ul class="fr-skiplinks__list">
      <li>
        <a class="fr-link" href="#contenu">Contenu de la démarche</a>
      </li>
      <li>
        <a class="fr-link" href="#header-navigation">Menu FAQ & Session FranceConnect</a>
      </li>
      <li>
        <a class="fr-link" href="#footer">Pied de page</a>
      </li>
    </ul>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <title><%= @browser_title %></title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "dsfr-fonts", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "dsfr", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "dsfr-utility", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_include_tag "dsfr.module", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>

    <%= render partial: 'shared/favicons' %>
    <%= render partial: 'layouts/analytics' %>
  </head>
  <body>
    <%= render partial: 'layouts/skiplinks' %>
    <%= render partial: 'shared/support_banner' %>
    <%= render partial: 'layouts/header' %>

    <main>
      <%= render partial: "layouts/banner" %>

      <div class="fr-container fr-my-6w" id="contenu">
        <%= render partial: "layouts/flash" %>
        <%= yield %>
      </div>
    </main>

    <%= yield :secondary_information %>
    <%= render partial: 'layouts/footer' %>
  </body>
</html>